language: python
python:
- '3.8'
install:
- pip install black
script:
- black --check ./
- python -m unittest tests/*

deploy:
  username: tamccall
  password:
    secure: gTcfgZxaXJvwYH9K/t2gigJcCZeU36PlwhxKGxnktu1RgJuZhsq//N2fOSbJehHPsVuIGAMo8rgZqgrDbN/YSkH7l2fbKPJsXq+tJIwpNtM2R9atrXiNAFovAr9hL4ojNInNmBZbm7LA/UEhMClVYbQ1IIwChBFHXg+ygvHMII0tZmDlbkoxKc8KMqklf9PggMN+fM+DxM0b6NlCSDwGas8mS5Yj3f9kVEFvQIwlcrBYPWruyZ2M8bDyigshBXp/4QQqvSotp2Jj7Onbr6nrCNT7PiEOGDavcqJ1oDSUoiRQqRzdM3XfwDDjQB6c9H1eCYt4zaCuAO0hSpogEIxXEJPC85x821WUqpt1M+vKJei6tCLGNmmqjzByV0oQVK/Wloy2DCIfc6z9XG2X5YN5yuPtICwm7PzzwlkV0xvQcgtU76c6HVP9iqx0qz3hKSr9ITpK5kR6alorbOTAjKFmZfmhKNuEnydhRmfHvM967eLiC7YmD57NH9P66KgLv5TyiK9qLV7fqPMRQKAz8qlYkIPy6TgqXSSwsm9CpUSbFT7UME3vFfbhszSAJEesLMd9cC+pgTbPdf/67K+fYFUZz/UFTcTswFjeikWLnT2QoBNOEy1pOgnOsuJkePtsQLTwRDskIeQwTrLsziMvKwmxFJBHPFqewBSxEmEVylUcCTU=
  on:
    tags: true
