language: python
python:
- '3.8'
install:
- pip install black
script:
- black --check ./
- python -m unittest tests/*
deploy:
  provider: pypi
  username: __token__
  password:
    secure: xRrF6nYPRbnG5fFYqUkI6rF2hoZcb12MMo5P/yMxlrT+9Xeubj80lZFkcJjrJsXHoPSJe07UDxZCl3KulmW3Tyr1h1NX/dPw0FqlP5x9ptX/QpF8KTWDelCAmuOn/+xDHIbjy04bL1aCwQhl7MAaFuKWTXL2jf8Xo5EGAVEaYzIENmcdYFo4Bitulyk05GK/FYd98Ohk1dRLSgMfLa4XBfjWZDTlmgb1TxKNg9FSgyfYmkyswSv5DkDUgxIgQVBNuD7c6RLVzrcCqo+JgoIUq/bc9XwhloRiyJtgbBptFY2uYyiM4pAlkLhq6Ud5Ofj7jgEMD2jqY5O8uTTsJKKrY/k0sa7Hc4mCqdwcU7WTxbrW3bHrP9TnkGC7Gu1H35eGl2iOSDQXURCWPMmPzUQBXI5Aga/a6AiZx7KHitfe4GBidAcBtRxpDEYnBf3IwqffyDJFMMhtjpUeSBToJVUFyXAkxmgJ/OqL0Pz9yCGBggBX1d44jBjNn0SvUSv3XpPAzBG4K/jyLyvfsYbH3myNZikL/Dxyk0QNVSaarJXK5QNMb5Lq2oeDtKgNB9brOy341Q6nfTmMa1+liV2XCxcAD5UXiQMujslEm55F8cRbQ1ajanbwiiKQAoFkxdqAL9kKh4lXmqTlp4/KQiODGCREh7VnGZLIQuI6nb64huD6Wqk=
  on:
    tags: true
